version: "3"

services:
  app:
    image: ghcr.io/khaledez/echoinfo:$IMAGE_VERSION
    ports:
     - "80:80"
    restart: always
    environment:
      - PORT=80
    healthcheck:
      test: ["CMD", "curl", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s