name: deploy docker
on:
  workflow_call:
    inputs:
      instance_ip:
        type: string
        required: true
      image_version:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      instance_ip:
        type: string
        required: true
      image_version:
        type: string
        required: true

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-docker-echoinfo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::427368570714:role/deploy-from-github
          aws-region: eu-west-2 # London
      - name: push credentials
        run: |
          aws ec2-instance-connect send-ssh-public-key --instance-id ${{ vars.INSTANCE_ID }} \
            --instance-os-user github --ssh-public-key '${{ vars.SSH_PUBLIC_KEY }}'
      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          host: ${{ inputs.instance_ip }}
          user: github
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: deploy
        run: |
          docker pull ghcr.io/khaledez/echoinfo:${{ inputs.image_version }}
          docker run -d -e PORT=80 -p 80:80 --restart always  ghcr.io/khaledez/echoinfo:${{ inputs.image_version }}

